### ISSUE TITLE
Document MistakeCheckers?

### ISSUE THREAD

**Issue by jcourt325** [project-viable/viable-virtual-lab#131]
Do we need to do more to document the design and specifics of the MistakeCheckers system?

@tylerhand1, you've been working on those more than me I think, so if we do need to write more for that system, I think you should be involved in writing that, or at the very least check my work, if you're able?

**Comment by tylerhand1** [comment]
I definitely agree we should document the design and specifics more, especially how to add a mistake checker. I think these instructions should be placed in the tutorial section.

I can take this on as I feel comfortable explaining it. I can let you know once I create a pull request to check it over and we can go from there if you're okay with that.

**Comment by tylerhand1** [comment]
On that note, as I was checking the lab log documentation, I noticed a couple things:
- There are two links to it from `index.md`
- Since the functionality of the lablogs changed to all show a popup, that needs to be documented as well
