### ISSUE TITLE
"Fill" Text above gel rig

### ISSUE THREAD

**Issue by ksnmoore** [project-viable/viable-virtual-lab#138]
Is there a purpose to this text? I couldn't get it to do anything and it doesn't seem to be aligned with our other stylistic changes that have been made.
<img width="171" alt="Screenshot 2024-08-13 at 1 55 39 PM" src="https://github.com/user-attachments/assets/244806a3-5285-415d-ab3b-d056b7823129">

**Comment by tylerhand1** [comment]
I don't believe it has a purpose anymore, so I removed the "Fill" text. I also noticed that the graduated cylinder can get stuck.
