### ISSUE TITLE
TAE addition to gel rig

### ISSUE THREAD

**Issue by ksnmoore** [project-viable/viable-virtual-lab#141]
If the gel has been added to the rig (not used to fill it, just added) and then TAE is added the menu to fill the gel rig doesn't appear, and instead the TAE just get automatically added to the rig (similar to how the gel gets added). When this happens the gel can't be run.

This feels like it may all be part of the same issue with filling the gel rig with the gel, so please combine if it makes sense to.

**Comment by tylerhand1** [comment]
They were somewhat similar, so I combined both issues into pull request #150. 

I won't close this issue for now, as I will wait for Jonas to do a code review for the pr to make sure I didn't miss anything.
