### ISSUE TITLE
Can't get rid of gel image from imager

### ISSUE THREAD

**Issue by ksnmoore** [project-viable/viable-virtual-lab#144]
Once gel is imaged in the imager that subscene can't be exited from.

UPDATE: there seem to be some random spots on the gel imager that I can click and the image will disappear (and reappear if I click in the same spot). Doesn't appear to be the entire imager just parts of it. If nothing else, we at least need directions on how to get out of this subscene

**Comment by tylerhand1** [comment]
I can take a look at this, since I've been working with the `GelImager` a lot recently with my other changes.
I'll make a branch based off the branch my changes are in as it will make it easier when all the changes I've made this week are merged into `dev`.

**Comment by jcourt325** [comment]
@tylerhand1 can this issue be closed?

**Comment by tylerhand1** [comment]
I think so, I just want to get feedback on it first before closing it.
