### ISSUE TITLE
Prepare for update

### ISSUE THREAD

**Issue by JRCockrum** [project-viable/viable-virtual-lab#185]
- Replace calls to deprecated tween node and OS time functions with Tweener or the Time singleton 
- rename external shaders from `.shader` to `.gdshader`
- Notable renames in shaders
      - Texture filter and repeat modes are now set on individual uniforms, rather than the texture files themselves.
      -hint_albedo is now source_color.
      -hint_color is now source_color.
      -Built in matrix variables were renamed.
      -Particles shaders no longer use the vertex() processor function. Instead they use start() and process().

**Comment by jakobrosencu** [comment]
After investigating the codebase, I couldn't find any code that needs to be updated for this ticket. The code makes no use of shader files that need to be renamed or "Tween nodes"/OS time functions.
