### ISSUE TITLE
Update tool keyword to @tool annotation

### ISSUE THREAD

**Issue by JRCockrum** [project-viable/viable-virtual-lab#187]
Replace all occurrences of the deprecated `tool` keyword with the new `@tool` annotation. verify that the script still performs as expected after the change 

**Scripts that need the change**
./project/source/Scripts/Boundaries/LabBoundary.gd
./project/source/Scripts/DimensionSprite.gd
./project/source/Scripts/Logger/ProcedureChecker.gd
./project/source/Scripts/Objects/CurrentConductor.gd
./project/source/Scripts/Objects/CurrentSource.gd
./project/source/Scripts/Objects/GelMoldSubsceneManager.gd
./project/source/Scripts/Objects/LabContainer.gd
./project/source/Scripts/Objects/LabObject.gd
./project/source/Scripts/Objects/ObjectSlot.gd
./project/source/Scripts/Objects/SourceContainer.gd
./project/source/Scripts/Objects/SubsceneManager.gd
./project/source/Scripts/Objects/VolumeContainer.gd
./project/source/Scripts/UI/ModuleSelectButton.gd
(I might have missed some files so double check)

**Comment by JRCockrum** [comment]
depends on #184

**Comment by EveDiby** [comment]
No instances of tool keyword found
