### ISSUE TITLE
Add "obvious" type annotations

### ISSUE THREAD

**Issue by harperstoeckle** [project-viable/viable-virtual-lab#198]
We should add type annotations in places where there is a clear type. There are a few places where it's less obvious how to add types; in particular, groups are used to indicate that a certain functions are expected to be implemented. For example, anything in the `Heatable` group is expected to implement the `heat` function, and any code that wants to heat something will first check that the object is in the `Heatable` group, then call `heat` on it. This is problematic because there's not really any way to enforce that those functions exist. Any solution to this is non-trivial, so we will have to figure that out separately.

**Comment by Drock54651** [comment]
Check this list for files where you added static typing to:

- [ ] AgarPowderSubstance.gd
- [ ] BinderSubstance.gd
- [ ] BufferSolution.gd
- [ ] Camera.gd
- [ ] ContactWire.gd
- [ ] CurrentChecker.gd
- [ ] CurrentConductor.gd
- [ ] CurrentContact.gd
- [ ] CurrentSource.gd
- [ ] DimensionSprite.gd
- [ ] Disposal.gd
- [ ] DNASubstance.gd
- [ ] DummyWeighable.gd
- [ ] ElectrodeTerminal.gd
- [ ] ElectrolysisSetup.gd
- [ ] GameSettingsSingleton.gd
- [ ] GelBand.gd
- [ ] GelDisplay.gd
- [ ] GelImager.gd
- [ ] GelMixManager.gd
- [ ] GelMixSubstance.gd
- [ ] GelMoldSubsceneManager.gd
- [ ] GelWell.gd
- [ ] GelWellPipetteProxy.gd
- [ ] GraduatedCylinder.gd
- [ ] HeatingTimeChecker.gd
- [ ] LabBoundary.gd
- [ ] LabContainer.gd
- [ ] LabLogSingleton.gd
- [ ] LabObject.gd
- [ ] Main.gd
- [ ] Menu.gd
- [ ] Microwave.gd
- [ ] MistakeChecker.gd
- [ ] MixManager.gd
- [ ] Mixtures.gd
- [ ] MixtureChecker.gd
- [ ] ModuleData.gd
- [ ] ModuleSelectButton.gd
- [ ] ObjectSlot.gd
- [ ] Pipette.gd
- [ ] PipetteDispenseChecker.gd
- [ ] ProcedureChecker.gd
- [ ] Scale.gd
- [ ] ScaleTesting.gd
- [ ] Scoopula.gd
- [ ] ScoopulaMenu.gd
- [ ] SourceContainer.gd
- [ ] Spawner.gd
- [ ] Substance.gd
- [ ] SubsceneManager.gd
- [ ] VolumeContainer.gd
- [ ] WeighBoat.gd
