### ISSUE TITLE
Document LabObject Groups

### ISSUE THREAD

**Issue by jcourt325** [project-viable/viable-virtual-lab#55]
I'm thinking a table, where each row is a type, listing the group name on the left, and a list of functions that it must implement on the right.

I know of at least these groups:
- Container
- Heatable
- Weighable
- LabObjects
- SubsceneManagers

We should also probably have a list of special one off groups, like "Gel Boat".

I think this Issue can mostly just be for adding a place in the documentation to list these.

**Comment by tylerhand1** [comment]
I agree that a table seems like an easy way to document these groups.

I do think we should have two separate tables instead of one, as some are substance-only like:
- Granular Substance
- Solid Substance
- Liquid Substance
- Etc.
