### ISSUE TITLE
Allow multiple attempts at correctly loading a well

### ISSUE THREAD

**Issue by jcourt325** [project-viable/viable-virtual-lab#57]
Right now, if you mess up loading a well at all, you can't do it again.

Ideally, I think you could try again, if you had inserted it too high the first time.

We need it to continue to not let you do it again if you break the well.

**Comment by jcourt325** [comment]
@ksnmoore and @jwtay1: do we need to do anything more complex to handle mistakes here?

For example, should pouring a sample over the top cause small amounts of it to contaminate the other wells? If so, all of them, or just adjacent ones or something?

**Comment by jwtay1** [comment]
I would suggest keeping things simple here - if the user misses the well by pipetting too high, then the sample is just lost. Same with pipetting too far down. 

Re trying again - I think that the way to reset would be to drag the gel boat into the trash, thereby throwing out the agarose gel and allowing the user to start again.
