### ISSUE TITLE
Pipettes can try to add a sample to the overall Gel Mold, instead of inserting it into a well

### ISSUE THREAD

**Issue by jcourt325** [project-viable/viable-virtual-lab#59]
You currently have to manually open the subscene. If you just drag the Pipette onto the mold, it will try to insert anyway because the Gel Mold is a container. It needs to remain a container because you have to be able to add the Gel Mixture itself.

By design, there's no way for the SubsceneManager to say "hey actually Pipette don't do your thing".

Maybe remove the "Container" group from the Gel Mold, once it should no longer be accepting things like that? This seems like it could cause weird behavior if the user does something incorrectly.

Maybe make the user open the subscene to fill the mold? This might need a little bit of UI guidance to make it clear what to do, and potentially require some changes to the Imaging functionality.

**Comment by jcourt325** [comment]
It could also be worth having the user insert the Comb within the subscene for consistency. Maybe even give it its own Proxy object to handle that? (See #63 as well?)

**Comment by jwtay1** [comment]
I think we should do something like the former. Better yet, dragging the pipette over the gel mold should open the pipetting subscene.
