### ISSUE TITLE
Should you be able to cool the gel mold repeatedly?

### ISSUE THREAD

**Issue by jcourt325** [project-viable/viable-virtual-lab#60]
Right now, once you hit the "Let Cool" button on the gel mold, it goes away forever. This seems undesirable.

My concerns are:
- It needs to be clear that you have actually done something. For now, the only way we indicate that the gel has cooled is by making the button go away.
- Do we even have a way of telling if a substance is above room temperature right now? If not, we can't make its visibility depend on whether it actually is hot.

A simple solution might be to make the button go away  when clicked, and reappear when the subscene is closed and reopened?

**Comment by jwtay1** [comment]
@jcourt325 Not sure if you've made a change here already but the way it works is good I think. The button should just disappear after the gel is cooled.
