### ISSUE TITLE
Correct parameters (volumes, etc)

### ISSUE THREAD

**Issue by jcourt325** [project-viable/viable-virtual-lab#64]
Right now we have arbitrary numbers in several places. Should we replace these with more correct values?

Off the top of my head:
- Volumes of Agarose and TAE Buffer to make the gel
- Volume of TAE Buffer to add to the electrolysis setup
- Volume of DNA samples to pipette
- Time to heat gel mixture
- Voltage to run the gel
- Time to run the gel
- Specific lengths of DNA samples (adding a Ladder is #51), but should the other samples correspond to something real, like human DNA or something?

Are there any other parameters that we should be thinking about?

**Comment by jwtay1** [comment]
- Volumes of Agarose and TAE Buffer to make the gel
    - This should affect the concentration of the gel and ultimately how quickly the bands move through the gel in the simulated results

- Volume of TAE Buffer to add to the electrolysis setup
-   https://www.bio-rad.com/en-us/product/mini-sub-cell-gt-systems?ID=bec92fc8-9963-42b2-82cd-9381accea8a3

-  Volume of DNA samples to pipette
  - The volume here should correspond to the size of the wells, which depends on the thickness of the gel/gel volume. Maybe for now we can set the maximum volume to be say 50 uL. Any more would spill over.

- Time to heat gel mixture
  - Great question. For now, why don't we fix the microwave time at 60 seconds.

Voltage to run the gel
Time to run the gel
- Typically these affect the speed of the band through the gel. Typical numbers are 120V for 20 mins but it depends on the gel concentration.

Specific lengths of DNA samples (adding a Ladder is https://github.com/project-viable/viable-virtual-lab/issues/51), but should the other samples correspond to something real, like human DNA or something?
- Let's not worry about this for now.

**Comment by ksnmoore** [comment]
Instructions text: 0.75 g of agarose and 50mL of TAE to make the gel
