### ISSUE TITLE
General scene setup

### ISSUE THREAD

**Issue by jwtay1** [project-viable/viable-virtual-lab#66]
Overall UI suggestions:

1. The scene is unnecessarily wide. We should have everything visible on a single screen (say 1920x1080).
2. Objects are not really scaled realistically, e.g. the gel rig is the same size as the microwave, the power supply box is too large. It doesn't have to be 100% accurate but the items should be scaled so it looks realistic.
3. Would be nice if we could put in the pipette rack.
4.  The bottom benches look blurry compared to the other items.
5. We don't need so many bins - let's just keep the biohazard one for now.
6. There needs to be some kind of background (even if it's just an off white wall) not just the default gray.

**Comment by jwtay1** [comment]
More graphics needed for splash screen to cover up all the default gray

**Comment by jcourt325** [comment]
7/22 meeting - 1280x720 might be a good resolution to try to be in the browser
