### ISSUE TITLE
Don't let pipette be thrown away

### ISSUE THREAD

**Issue by jwtay1** [project-viable/viable-virtual-lab#91]

**Comment by jwtay1** [comment]
Lab objects should not be allowed to be thrown away.

**Comment by jcourt325** [comment]
Disposals should take either a list of Object groups that they _can_ accept, or a list of groups that they _can't_, and those groups should be applied to objects as needed, or maybe both?

This should be a pretty quick change. We'll also need to document those groups in the LabObject Groups documentation, and the details of how a disposal determines whether it can take an object in multiple of the above groups.
